version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/vue-todo-app
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    volumes:
      - ./frontend/vue-todo-app:/app
      - /app/node_modules
    command: npm run serve
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend/TodoApi
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - todo-data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    networks:
      - app-network

volumes:
  todo-data:

networks:
  app-network:
