version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/vue-todo-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/vue-todo-app:/app
      - /app/node_modules
    command: npm run serve
    depends_on:
      - backend

  backend:
    build:
      context: ./backend/TodoApi
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - todo-data:/var/lib/postgresql/data

volumes:
  todo-data:
